# -*- coding: utf-8 -*-
"""
HorizontalNGrams.py
===================

Filters a horizontal interval indexers output.

Author: Reiner Kramer	
Email: reiner@music.org
Updated: 06.01.2016

"""

import sys, os, music21, pyext, pandas

from vis.analyzers.indexers import noterest, interval

try:
	print("HorizontalNGrams.py was loaded.")
except:
	print("Loading HorizontalNGrams.py failed.")

class Get(pyext._class):
	"""
	Horizontal NGrams Module
	================================

	Get
	---

	Processes a DataFrame generated by the HorizontalIntervalIndexer, parses 
	it, and creates a new DataFrame that shows all the horizontal NGrams in a 
	particular part or stream. The main input type (inlet 1) is a 
	horizontal interval indexed pickled DataFrame.
	"""
	_inlets = 2
	_outlets = 1

	def __init__(self,
		df_paths=0,
		df_scores=0,
		ngrams=0,
		sample_rate=3):
		"""
		Storing variables used in this class.
		"""
		self.df_paths = df_paths
		self.df_scores = df_scores
		self.ngrams = ngrams
		self.sample_rate = sample_rate


	def _anything_1(self,*df_paths):
		"""
		Parses a note-rest-indexed DataFrame and show horizontal intervals.
		"""
		
		try:

			# Convert paths into real strings:
			self.df_paths = [str(x) for x in df_paths]
			
			# Generate scores from paths:
			self.df_scores = [pandas.read_pickle(x) for x in self.df_paths]

			# Build N-Grams from scores:
			self.ngrams = [self._horizontal_ngrams(x, self.sample_rate)
				for x in self.df_scores]
			
			# Remove Duplicates from N-Grams:
			self.ngrams_reduced = [self._count_unique_ngrams(x, ordered=True) 
				for x in self.ngrams]
			
			# Print N-Grams to Pd Window:
			self._print_ngrams(self.df_paths,self.ngrams_reduced)

		except Exception as e:
			
			print(e)

	def _anything_2(self,sample_rate):
		"""
		Changes the sample rate of ngrams.
		"""
		if(self.df_scores == 0):
			
			print("Please load horizontal interval indexed Dataframes first.")
		
		else:

			try:

				# Apply new N-Gram length, i.e. sample rate:
				self.sample_rate = int(sample_rate)

				# Generate N-Grams:
				self.ngrams = [self._horizontal_ngrams(x, self.sample_rate)
					for x in self.df_scores]
				
				# Remove Duplicates from N-Grams:
				self.ngrams_reduced = [self._count_unique_ngrams(x, ordered=True) 
					for x in self.ngrams]

				# Print N-Grams to Pd Window:
				self._print_ngrams(self.df_paths,self.ngrams_reduced)

			except Exception as e:
			
				print(e)

	def _horizontal_ngrams(self, hint_scores, sample_rate):
		"""
		Creates horizontal ngrams.
		"""

		# Remove rests:
		hint_cols = [str(x) 
			for x in hint_scores['Part']['0']
			if (str(x) != 'Rest')]

		# Add sample rate:
		hint_cols_ng = [hint_cols[x:(x+sample_rate)] 
			for x in range(len(hint_cols))
			if (x < (len(hint_cols) - (sample_rate - 1)))]

		return hint_cols_ng
	
	def _count_unique_ngrams(self,hints_ngrams,ordered=True):
		"""
		Counts N-Grams, removes duplicates, and sorts them in order of frequency.
		"""

		# Count N-Grams:
		counted_ngrams = [(x, hints_ngrams.count(x)) for x in hints_ngrams]
		
		# Removed N-Grams
		reduced_ngrams = [eval(y) for y in set([str(x) for x in counted_ngrams])]

		# Order N-Grams by frequency of occurence if so desired:
		if(ordered == True):
			
			ordered_ngrams = sorted(reduced_ngrams, 
				key=lambda x: x[1], 
				reverse=True)
			
			return ordered_ngrams
		
		else:
			
			return reduced_ngrams

	def _print_ngrams(self, df_paths, ngrams_reduced):
		"""
		Prints NGrams in a readable format.
		"""
		for x, y in zip(df_paths,ngrams_reduced):
			self._generate_name(x)
			for z in y:
				print(str(z[0]) + ': ' + str(z[1]))

	def _generate_name(self,path):
		"""
		Private method to generate a human readable name of a composition from
		it path. This method need to be improved and use meta data rather than
		generate metadata from a file string ...
		"""
		file_name = os.path.split(path)
		file_extr = os.path.splitext(file_name[1])
		strip_name = str(file_extr[0]).replace("-"," ").replace("_",": ")
		comp_name = strip_name.replace("Hint: ","")

		print("\n{0}\n{1}".format(comp_name, (len(comp_name) * "-")))


	def _msg_missing_scores(self):
		"""
		Method to indicate that no DataFrames have been loaded.
		"""
		return "Please load (a) note-rest-indexed DataFrame(s) first."
