# -*- coding: utf-8 -*-
"""
NGramIndexer.py
===============

A Python object to interpret a vertical and horizontal NoteRestIndexed 
DataFrame in Pd. A new DataFrame is created to find NGrams, which combines 
horizontal intervals with vertical intervals.

Author: Reiner Kramer	
Email: reiner@music.org
Updated: 04.30.2016

"""

import sys, os, music21, pyext, pandas
from vis.analyzers.indexers import noterest, interval, offset, ngram

try:
	print("NGramIndexer.py was loaded.")
except:
	print("Loading the NGramIndexer.py failed.")

class Get(pyext._class):
	"""
	NGramIndexer Module
	===================

	Get
	---

	Processes two DataFrames generated by the HorizontalIntervalIndexer, and 
	the VerticalIntervalIndexer respectively, parses them, and creates a NGram 
	DataFrame.
	
	Inlets:
	1. A pickled horizontal interval DataFrame.
	2. A pickled vertical interval DataFrame.

	@TODO: merge pandas dataframes pandas.concat([list of dataframes]) 

	"""
	_inlets = 3
	_outlets = 3

	def __init__(self,hint_paths=0,vint_paths=0,ngrams_df=0):
		"""
		Storing variables used in this class.
		"""
		self.hint_paths = hint_paths
		self.vint_paths = vint_paths
		self.ngrams_df = ngrams_df

	def _anything_1(self,*hint_df):
		"""
		Parses a horizontal interval DataFrame.
		"""
		
	def _anything_2(self,*vint_df):
		"""
		Parses a vertical interval DataFrame.
		"""


